### ISSUE TITLE
Fatal error: 'git2.h' file not found

### ISSUE THREAD

**Issue by christhekeele** [saleyn/egit#3]
### Environment

- CPU: M2
- OS: OSX
- elixir: asdf 1.14.3-otp-25
- erlang: asdf 25.2.3
- egit: `[b29ba41](https://github.com/saleyn/egit/commit/b29ba416473d478915be59418d12011b1b0b279d)`
- libgit2: homebrew 1.5.2

### Error

After adding `{:egit, github: "saleyn/egit", ref: "b29ba41"}` to my `mix.exs` deps and running `mix install` successfully, upon initial compile, I get:

```
==> Updating fmt submodule
c++ -mavx2 -finline-functions -Wall -std=c++20 -pie -O3 -DNDEBUG -fPIC -I/Users/keele/.config/asdf/data/installs/erlang/25.2.3/erts-13.1.5/include -I/Users/keele/.config/asdf/data/installs/erlang/25.2.3/lib/erl_interface-5.3/include -I/usr/local/opt/openssl@1.1/include -DFMT_HEADER_ONLY -Ifmt/include -Wno-array-bounds -Wno-stringop-overflow   -c -o /Users/keele/Projects/personal/site/deps/egit/c_src/git.o /Users/keele/Projects/personal/site/deps/egit/c_src/git.cpp
clang: warning: argument unused during compilation: '-mavx2' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
/Users/keele/Projects/personal/site/deps/egit/c_src/git.cpp:24:10: fatal error: 'git2.h' file not found
#include <git2.h>
         ^~~~~~~~
1 warning and 1 error generated.
make: *** [/Users/keele/Projects/personal/site/deps/egit/c_src/git.o] Error 1
===> Hook for compile failed!

** (Mix) Could not compile dependency :egit, "/Users/keele/.mix/elixir/1-14/rebar3 bare compile --paths /Users/keele/Projects/personal/site/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile egit", update it with "mix deps.update egit" or clean it with "mix deps.clean egit"```

**Comment by christhekeele** [comment]
Tried ditching homebrew's outdated libgit2 and compiling from source following [these instructions](https://github.com/saltstack/salt/issues/61633#issuecomment-1116724321) with some modifications:

```
brew install cmake
git clone git@github.com:libgit2/libgit2.git
cd libgit2
git checkout v1.6.4
mkdir build
cd build
cmake ..
cmake --build .
sudo cmake --build . --target install
```

This results in a more interesting error:

```
==> Updating fmt submodule
c++ -mavx2 -finline-functions -Wall -std=c++20 -pie -O3 -DNDEBUG -fPIC -I/Users/keele/.config/asdf/data/installs/erlang/25.2.3/erts-13.1.5/include -I/Users/keele/.config/asdf/data/installs/erlang/25.2.3/lib/erl_interface-5.3/include -I/usr/local/opt/openssl@1.1/include -DFMT_HEADER_ONLY -Ifmt/include -Wno-array-bounds -Wno-stringop-overflow   -c -o /Users/keele/Projects/personal/site/deps/egit/c_src/git.o /Users/keele/Projects/personal/site/deps/egit/c_src/git.cpp
clang: warning: argument unused during compilation: '-mavx2' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
In file included from /Users/keele/Projects/personal/site/deps/egit/c_src/git.cpp:24:
In file included from /usr/local/include/git2.h:11:
In file included from /usr/local/include/git2/annotated_commit.h:11:
In file included from /usr/local/include/git2/repository.h:11:
In file included from /usr/local/include/git2/types.h:70:
/usr/local/include/git2/oid.h:45:9: warning: 'GIT_OID_SHA1_HEXSIZE' macro redefined [-Wmacro-redefined]
#define GIT_OID_SHA1_HEXSIZE   (GIT_OID_SHA1_SIZE * 2)
        ^
/Users/keele/Projects/personal/site/deps/egit/c_src/git.cpp:17:9: note: previous definition is here
#define GIT_OID_SHA1_HEXSIZE GIT_OID_HEXSZ
        ^
In file included from /Users/keele/Projects/personal/site/deps/egit/c_src/git.cpp:25:
/Users/keele/Projects/personal/site/deps/egit/c_src/git_utils.hpp:190:46: error: use of undeclared identifier 'ERL_NIF_UTF8'
  if (!enif_get_atom_length(env, atom, &len, ERL_NIF_UTF8))
                                             ^
/Users/keele/Projects/personal/site/deps/egit/c_src/git_utils.hpp:193:50: error: use of undeclared identifier 'ERL_NIF_UTF8'
  if (!enif_get_atom(env, atom, s.data(), len+1, ERL_NIF_UTF8)) [[unlikely]]
                                                 ^
/Users/keele/Projects/personal/site/deps/egit/c_src/git_utils.hpp:305:54: error: no matching function for call to 'enif_get_long'
  auto res = enif_is_identical(kv[0], match_term) && enif_get_int64(env, kv[1], &v);
                                                     ^~~~~~~~~~~~~~
/Users/keele/.config/asdf/data/installs/erlang/25.2.3/erts-13.1.5/include/erl_nif_api_funcs.h:653:26: note: expanded from macro 'enif_get_int64'
#  define enif_get_int64 enif_get_long
                         ^~~~~~~~~~~~~
/Users/keele/.config/asdf/data/installs/erlang/25.2.3/erts-13.1.5/include/erl_nif_api_funcs.h:104:27: note: candidate function not viable: no known conversion from 'int64_t *' (aka 'long long *') to 'long *' for 3rd argument
ERL_NIF_API_FUNC_DECL(int,enif_get_long,(ErlNifEnv*, ERL_NIF_TERM term, long* ip));
                          ^
/Users/keele/.config/asdf/data/installs/erlang/25.2.3/erts-13.1.5/include/erl_nif.h:359:71: note: expanded from macro 'ERL_NIF_API_FUNC_DECL'
#  define ERL_NIF_API_FUNC_DECL(RET_TYPE, NAME, ARGS) extern RET_TYPE NAME ARGS
                                                                      ^
2 warnings and 3 errors generated.
make: *** [/Users/keele/Projects/personal/site/deps/egit/c_src/git.o] Error 1
===> Hook for compile failed!

** (Mix) Could not compile dependency :egit, "/Users/keele/.mix/elixir/1-14/rebar3 bare compile --paths /Users/keele/Projects/personal/site/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile egit", update it with "mix deps.update egit" or clean it with "mix deps.clean egit"
```

**Comment by christhekeele** [comment]
Is there a specific version of `libgit2` or `erl` I should be targeting?

**Comment by saleyn** [comment]
I have libgit2 1.6.4, but that is not a requirement.  Please check the latest commit.

**Comment by christhekeele** [comment]
That changed things! I now seem to be getting an error that is architecture-specific. I'll post it here for posterity, but I doubt this is an egit issue at this point. Thanks for the help.

```
==> Updating fmt submodule
c++ -mavx2 -finline-functions -Wall -std=c++20 -pie -O3 -DNDEBUG -fPIC -I/Users/keele/.config/asdf/data/installs/erlang/25.2.3/erts-13.1.5/include -I/Users/keele/.config/asdf/data/installs/erlang/25.2.3/lib/erl_interface-5.3/include -I/usr/local/opt/openssl@1.1/include -DFMT_HEADER_ONLY -Ifmt/include -Wno-array-bounds -Wno-stringop-overflow   -c -o /Users/keele/Projects/personal/site/deps/egit/c_src/git.o /Users/keele/Projects/personal/site/deps/egit/c_src/git.cpp
clang: warning: argument unused during compilation: '-mavx2' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
In file included from /Users/keele/Projects/personal/site/deps/egit/c_src/git.cpp:36:
/Users/keele/Projects/personal/site/deps/egit/c_src/git_remote.hpp:38:16: warning: variable 'kind' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
    } else if (enif_is_identical(tagvals[0], ATOM_SETURL) && enif_inspect_binary(env, tagvals[1], &bin)) {
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/keele/Projects/personal/site/deps/egit/c_src/git_remote.hpp:52:11: note: uninitialized use occurs here
  switch (kind) {
          ^~~~
/Users/keele/Projects/personal/site/deps/egit/c_src/git_remote.hpp:38:12: note: remove the 'if' if its condition is always true
    } else if (enif_is_identical(tagvals[0], ATOM_SETURL) && enif_inspect_binary(env, tagvals[1], &bin)) {
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/keele/Projects/personal/site/deps/egit/c_src/git_remote.hpp:38:16: warning: variable 'kind' is used uninitialized whenever '&&' condition is false [-Wsometimes-uninitialized]
    } else if (enif_is_identical(tagvals[0], ATOM_SETURL) && enif_inspect_binary(env, tagvals[1], &bin)) {
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/keele/Projects/personal/site/deps/egit/c_src/git_remote.hpp:52:11: note: uninitialized use occurs here
  switch (kind) {
          ^~~~
/Users/keele/Projects/personal/site/deps/egit/c_src/git_remote.hpp:38:16: note: remove the '&&' if its condition is always true
    } else if (enif_is_identical(tagvals[0], ATOM_SETURL) && enif_inspect_binary(env, tagvals[1], &bin)) {
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/keele/Projects/personal/site/deps/egit/c_src/git_remote.hpp:24:3: note: variable 'kind' is declared here
  RemoteOp                kind;
  ^
/Users/keele/Projects/personal/site/deps/egit/c_src/git_remote.hpp:49:40: warning: variable 'opt' is uninitialized when used here [-Wuninitialized]
    return raise_badarg_exception(env, opt);
                                       ^~~
/Users/keele/Projects/personal/site/deps/egit/c_src/git_remote.hpp:21:30: note: initialize the variable 'opt' to silence this warning
  ERL_NIF_TERM            opt;
                             ^
                              = 0
4 warnings generated.
c++ /Users/keele/Projects/personal/site/deps/egit/c_src/git.o -L/usr/local/opt/openssl@1.1/lib -L/Users/keele/.config/asdf/data/installs/erlang/25.2.3/lib/erl_interface-5.3/lib -lei -lgit2 -shared -o /Users/keele/Projects/personal/site/deps/egit/priv/git.so
ld: warning: directory not found for option '-L/usr/local/opt/openssl@1.1/lib'
Undefined symbols for architecture arm64:
  "_enif_alloc_resource", referenced from:
      to_monitored_resource(enif_environment_t*, git_repository*) in git.o
  "_enif_get_atom", referenced from:
      atom_to_str(enif_environment_t*, unsigned long) in git.o
  "_enif_get_atom_length", referenced from:
      atom_to_str(enif_environment_t*, unsigned long) in git.o
  "_enif_get_int", referenced from:
      lg2_rev_parse(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_rev_list(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_branch_list(enif_environment_t*, git_repository*, unsigned long) in git.o
      lg2_index(enif_environment_t*, git_repository*, unsigned long) in git.o
      cat_file_nif(enif_environment_t*, int, unsigned long const*) in git.o
  "_enif_get_list_cell", referenced from:
      lg2_add(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_checkout(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_rev_parse(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_rev_list(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_branch_list(enif_environment_t*, git_repository*, unsigned long) in git.o
      lg2_branch(enif_environment_t*, git_repository*, unsigned long, unsigned long, unsigned long) in git.o
      lg2_index(enif_environment_t*, git_repository*, unsigned long) in git.o
      ...
  "_enif_get_long", referenced from:
      lg2_tag(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) in git.o
  "_enif_get_resource", referenced from:
      lg2_config(enif_environment_t*, unsigned long, unsigned long, unsigned long) in git.o
      fetch_nif(enif_environment_t*, int, unsigned long const*) in git.o
      add_nif(enif_environment_t*, int, unsigned long const*) in git.o
      checkout_nif(enif_environment_t*, int, unsigned long const*) in git.o
      push_nif(enif_environment_t*, int, unsigned long const*) in git.o
      commit_nif(enif_environment_t*, int, unsigned long const*) in git.o
      commit_lookup_nif(enif_environment_t*, int, unsigned long const*) in git.o
      ...
  "_enif_get_tuple", referenced from:
      lg2_rev_parse(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_rev_list(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_branch_list(enif_environment_t*, git_repository*, unsigned long) in git.o
      lg2_branch(enif_environment_t*, git_repository*, unsigned long, unsigned long, unsigned long) in git.o
      lg2_index(enif_environment_t*, git_repository*, unsigned long) in git.o
      lg2_remote(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) in git.o
      lg2_tag(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) in git.o
      ...
  "_enif_inspect_binary", referenced from:
      lg2_add(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_rev_list(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_config(enif_environment_t*, unsigned long, unsigned long, unsigned long) in git.o
      lg2_branch(enif_environment_t*, git_repository*, unsigned long, unsigned long, unsigned long) in git.o
      lg2_remote(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) in git.o
      lg2_tag(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) in git.o
      lg2_status(enif_environment_t*, git_repository*, unsigned long) in git.o
      ...
  "_enif_is_atom", referenced from:
      parse_atom_if(enif_environment_t*, unsigned long, unsigned long const*, unsigned long&) in git.o
      lg2_status(enif_environment_t*, git_repository*, unsigned long) in git.o
      remote_nif(enif_environment_t*, int, unsigned long const*) in git.o
      tag_nif(enif_environment_t*, int, unsigned long const*) in git.o
  "_enif_is_identical", referenced from:
      parse_atom_if(enif_environment_t*, unsigned long, unsigned long const*, unsigned long&) in git.o
      lg2_add(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_checkout(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_rev_parse(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_rev_list(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_config(enif_environment_t*, unsigned long, unsigned long, unsigned long) in git.o
      lg2_branch_list(enif_environment_t*, git_repository*, unsigned long) in git.o
      ...
  "_enif_is_list", referenced from:
      lg2_branch(enif_environment_t*, git_repository*, unsigned long, unsigned long, unsigned long) in git.o
      lg2_index(enif_environment_t*, git_repository*, unsigned long) in git.o
      lg2_status(enif_environment_t*, git_repository*, unsigned long) in git.o
      init_nif(enif_environment_t*, int, unsigned long const*) in git.o
      add_nif(enif_environment_t*, int, unsigned long const*) in git.o
      checkout_nif(enif_environment_t*, int, unsigned long const*) in git.o
      push_nif(enif_environment_t*, int, unsigned long const*) in git.o
      ...
  "_enif_is_tuple", referenced from:
      remote_nif(enif_environment_t*, int, unsigned long const*) in git.o
  "_enif_make_atom", referenced from:
      cat_file_nif(enif_environment_t*, int, unsigned long const*) in git.o
      init_atoms(enif_environment_t*) in git.o
  "_enif_make_badarg", referenced from:
      lg2_config(enif_environment_t*, unsigned long, unsigned long, unsigned long) in git.o
      lg2_branch(enif_environment_t*, git_repository*, unsigned long, unsigned long, unsigned long) in git.o
      lg2_tag(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) in git.o
      init_nif(enif_environment_t*, int, unsigned long const*) in git.o
      clone_nif(enif_environment_t*, int, unsigned long const*) in git.o
      open_nif(enif_environment_t*, int, unsigned long const*) in git.o
      fetch_nif(enif_environment_t*, int, unsigned long const*) in git.o
      ...
  "_enif_make_int", referenced from:
      lg2_checkout(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_branch_list(enif_environment_t*, git_repository*, unsigned long) in git.o
      lg2_index(enif_environment_t*, git_repository*, unsigned long) in git.o
      cat_file_nif(enif_environment_t*, int, unsigned long const*) in git.o
      print_signature(enif_environment_t*, git_signature const*) in git.o
  "_enif_make_list", referenced from:
      lg2_index(enif_environment_t*, git_repository*, unsigned long) in git.o
      lg2_tag(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) in git.o
  "_enif_make_list_from_array", referenced from:
      lg2_add(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_rev_list(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_branch_list(enif_environment_t*, git_repository*, unsigned long) in git.o
      lg2_index(enif_environment_t*, git_repository*, unsigned long) in git.o
      lg2_remote(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) in git.o
      lg2_remotes_list(enif_environment_t*, git_repository*) in git.o
      lg2_tag(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) in git.o
      ...
  "_enif_make_long", referenced from:
      lg2_index(enif_environment_t*, git_repository*, unsigned long) in git.o
      cat_file_nif(enif_environment_t*, int, unsigned long const*) in git.o
      commit_lookup_nif(enif_environment_t*, int, unsigned long const*)::$_9::operator()(unsigned long, long long) const in git.o
      print_signature(enif_environment_t*, git_signature const*) in git.o
  "_enif_make_map_from_arrays", referenced from:
      lg2_add(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_checkout(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_rev_parse(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_index(enif_environment_t*, git_repository*, unsigned long) in git.o
      lg2_status(enif_environment_t*, git_repository*, unsigned long) in git.o
      commit_lookup_nif(enif_environment_t*, int, unsigned long const*) in git.o
      cat_file_nif(enif_environment_t*, int, unsigned long const*) in git.o
      ...
  "_enif_make_new_binary", referenced from:
      visit_matched_cb(char const*, char const*, void*) in git.o
      make_git_error(enif_environment_t*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in git.o
      lg2_checkout(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_commit(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in git.o
      lg2_rev_parse(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_rev_list(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_config(enif_environment_t*, unsigned long, unsigned long, unsigned long) in git.o
      ...
  "_enif_make_resource", referenced from:
      to_monitored_resource(enif_environment_t*, git_repository*) in git.o
  "_enif_make_tuple", referenced from:
      lg2_add(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      make_git_error(enif_environment_t*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in git.o
      lg2_checkout(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_commit(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in git.o
      lg2_rev_parse(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_rev_list(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_config(enif_environment_t*, unsigned long, unsigned long, unsigned long) in git.o
      ...
  "_enif_monitor_process", referenced from:
      to_monitored_resource(enif_environment_t*, git_repository*) in git.o
  "_enif_open_resource_type_x", referenced from:
      load(enif_environment_t*, void**, unsigned long) in git.o
  "_enif_raise_exception", referenced from:
      lg2_add(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_checkout(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_rev_parse(enif_environment_t*, git_repository*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long) in git.o
      lg2_rev_list(enif_environment_t*, git_repository*, unsigned long, unsigned long) in git.o
      lg2_config(enif_environment_t*, unsigned long, unsigned long, unsigned long) in git.o
      lg2_branch_list(enif_environment_t*, git_repository*, unsigned long) in git.o
      lg2_branch(enif_environment_t*, git_repository*, unsigned long, unsigned long, unsigned long) in git.o
      ...
  "_enif_release_resource", referenced from:
      to_monitored_resource(enif_environment_t*, git_repository*) in git.o
      resource_down(enif_environment_t*, void*, ErlNifPid*, ErlDrvMonitor*) in git.o
  "_enif_self", referenced from:
      to_monitored_resource(enif_environment_t*, git_repository*) in git.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/keele/Projects/personal/site/deps/egit/priv/git.so] Error 1
===> Hook for compile failed!

** (Mix) Could not compile dependency :egit, "/Users/keele/.mix/elixir/1-14/rebar3 bare compile --paths /Users/keele/Projects/personal/site/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile egit", update it with "mix deps.update egit" or clean it with "mix deps.clean egit"
```

**Comment by saleyn** [comment]
Fixed warnings, but the missing references likely indicate that you have a wrong architecture erlang install in `/home/serge/.asdf/installs/erlang/26.0/lib/erl_interface-5.4/lib`

**Comment by saleyn** [comment]
@christhekeele, let me know if this got fixed, so that we can close the issue.

**Comment by christhekeele** [comment]
Hey @saleyn! No luck I'm afraid. I am still getting the same error on your latest commit—minus warnings though!

> The missing references likely indicate that you have a wrong architecture erlang install

I do not think so... the Apple M2 Max chip is arm64:

```sh
uname -m
#=> arm64
```

My erlang seems to have been built appropriately:

```erl
erlang:system_info(system_architecture).
%=> "aarch64-apple-darwin22.3.0"
```

And the egit compilation pass does seem to be setting the correct path to my to my installation's `erl_interface` in the `LDFLAGS`: 

```sh
asdf which erl
#=> /Users/keele/.config/asdf/data/installs/erlang/25.2.3/bin/erl
# Compare to the -L path in the c++  build command:
#=> /Users/keele/.config/asdf/data/installs/erlang/25.2.3/lib/erl_interface-5.3/lib
```

I'm not really sure how to proceed debugging further. The only other references I've found online citing this issue are in `emqx` [here](https://github.com/emqx/emqx/issues?q=_enif_alloc_resource). These all describe messing with `LDFLAGS` until erl25 support for JIT on OSX M2s is released, which was a while ago.

**Comment by saleyn** [comment]
I think I found the culprit in the Makefile - there was an [extra space](https://github.com/saleyn/egit/commit/79753f06afae641f598ba1f7c6df3e697816eb30).  @christhekeele, please pull and build. 

If that doesn't help, what does `uname -s` return on your computer?

**Comment by christhekeele** [comment]
That does seem to help! `uname -s` does indeed return `Darwin`.

<details>
<summary>Edit: bad information</summary>

~~Now I'm getting:~~

```
==> Updating fmt submodule
fatal: Unable to find current revision in submodule path 'fmt'
make: *** [/Users/keele/Projects/personal/site/deps/egit/c_src/git.o] Error 128
===> Hook for compile failed!

** (Mix) Could not compile dependency :egit, "/Users/keele/.mix/elixir/1-14/rebar3 bare compile --paths /Users/keele/Projects/personal/site/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile egit", update it with "mix deps.update egit" or clean it with "mix deps.clean egit"
```

</details>

Thanks again for all the help!

**Comment by saleyn** [comment]
@christhekeele, have you tried what the compiler suggests:
```bash
$ mix deps.clean egit
$ rm -fr deps/egit
$ mix deps.update egit
```
I cannot reproduce this locally.

**Comment by christhekeele** [comment]
@saleyn I have been trying to remember to do that between each error report—I just ran it again and verified I am still experiencing the latest reported issue.

> I cannot reproduce this locally.

I know how frustrating that is, and irritating to try to debug remotely, asynchronously. I really appreciate your efforts so far, and would be happy to sit down with you for a screenshare sometime if you would like a quicker feedback loop for troubleshooting.

**Comment by saleyn** [comment]
@christhekeele, let me know your availability for this tonight after 4pm EDT.

**Comment by saleyn** [comment]
@christhekeele, I think I fixed the issue. Please check.

**Comment by christhekeele** [comment]
Hooray, it compiles! Thanks again!
